AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - REST API regional with Lambda proxy integration

Resources:
#Lambda function
  Service1LambdaRegionalApi:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.lambda_handler
      InlineCode: |
        import json
        import os

        def lambda_handler(event, context):
            return {
        "statusCode": 200,
        "body": json.dumps({
          "service" : "service1",
          "region" : os.environ['AWS_REGION']}),
        }
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api 
          Properties: 
            Path: /
            Method: get
            RestApiId:
              Ref: Service1ApiRegional
  Service2LambdaRegionalApi:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.lambda_handler
      InlineCode: |
        import json
        import os

        def lambda_handler(event, context):
            return {
        "statusCode": 200,
        "body": json.dumps({
          "service" : "service2",
          "region" : os.environ['AWS_REGION']}),
        }
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api 
          Properties: 
            Path: /
            Method: get
            RestApiId:
              Ref: Service2ApiRegional
              
  #REST Regional API
  Service1ApiRegional:
    Type: AWS::Serverless::Api
    Properties:
      Name: service1
      StageName: prod
      EndpointConfiguration: REGIONAL
  Service2ApiRegional:
    Type: AWS::Serverless::Api
    Properties:
      Name: service2
      StageName: prod
      EndpointConfiguration: REGIONAL

# Output with API URL
Outputs:
  Service1EndpointUrl:
    Description: 'REST regional endpoint URL'
    Value: !Sub 'https://${Service1ApiRegional}.execute-api.${AWS::Region}.amazonaws.com/prod'
  Service2EndpointUrl:
    Description: 'REST regional endpoint URL'
    Value: !Sub 'https://${Service2ApiRegional}.execute-api.${AWS::Region}.amazonaws.com/prod'

