AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - REST API regional with Lambda proxy integration


Resources:
  MultiRegionApisCluster:
    Type: AWS::Route53RecoveryControl::Cluster
    Properties:
      Name: multi-region-apis-cluster
  Service1ControlPanel:
    Type: AWS::Route53RecoveryControl::ControlPanel
    DependsOn:
      - MultiRegionApisCluster
    Properties:
      Name: Service1ControlPanel
      ClusterArn: !Ref MultiRegionApisCluster

  Service1RoutingControlPrimary:
    Type: AWS::Route53RecoveryControl::RoutingControl
    DependsOn:
      - MultiRegionApisCluster
      - Service1ControlPanel
    Properties:
      ClusterArn: !Ref MultiRegionApisCluster
      ControlPanelArn: !Ref Service1ControlPanel
      Name: service1-primary-rc

  Service1PrimaryHealthCheck:
    Type: AWS::Route53::HealthCheck
    DependsOn:
      - Service1RoutingControlPrimary
    Properties:
      HealthCheckConfig:
        Type: RECOVERY_CONTROL
        RoutingControlArn: !Ref Service1RoutingControlPrimary

  Service1RoutingControlSecondary:
    Type: AWS::Route53RecoveryControl::RoutingControl
    DependsOn:
      - MultiRegionApisCluster
      - Service1ControlPanel
    Properties:
      ClusterArn: !Ref MultiRegionApisCluster
      ControlPanelArn: !Ref Service1ControlPanel
      Name: service1-secondary-rc

  Service1SecondaryHealthCheck:
    Type: AWS::Route53::HealthCheck
    DependsOn:
      - Service1RoutingControlSecondary
    Properties:
      HealthCheckConfig:
        Type: RECOVERY_CONTROL
        RoutingControlArn: !Ref Service1RoutingControlSecondary

# Outputs
# Outputs:
#   EndpointUrl:
#     Description: 'REST regional endpoint URL'
#     Value: !Sub 'https://${ApiRegional}.execute-api.${AWS::Region}.amazonaws.com/prod'
#   # Custom Domain Name endpoint to be used during tests
#   CustomDomainNameEndpoint:
#     Description: Custom Domain Name endpoint
#     Value: !Sub "https://${DomainName}"

